name: "Eric Su"
description: "Eric Su of Boston, MA. MBA, Software Engineer, and Triathlete."

highlighter: rouge
paginate: 10
paginate_path: "/blog/page:num/"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
