name: "Eric Su"
description: "Eric Su of Boston, MA. Programmer, Photographer and Triathlete."

highlighter: "pygments"
paginate: 10

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"